### ISSUE TITLE
Increase readme infos

### ISSUE THREAD

**Issue by Its-Alex** [ggerganov/kbd-audio#1]
Can you provide info about project please:

- Is it cross-platform ?
- How can we build it ?

**Comment by ggerganov** [comment]
Add some short build instructions. Will add more details soon

**Comment by ggerganov** [comment]
I am able to build and run the project on Linux and Mac OS. I don't have a Windows machine to play with, so currently I cannot add build instructions for it. I guess there might be some parts of the code that will have to be ported to Windows. For example, the **record.cpp** includes:

    #include <termios.h>
    #include <unistd.h>

These are used to synchronise the audio capture with the keypress events in order to generate training data. Don't think these are available on Windows.

**Comment by Its-Alex** [comment]
When I follow your step to build project I have this issue

```
➜  build git:(master) ✗ make
Scanning dependencies of target Core
[  2%] Building CXX object CMakeFiles/Core.dir/audio_logger.cpp.o
[  5%] Linking CXX static library libCore.a
[  5%] Built target Core
Scanning dependencies of target record-full
[  7%] Building CXX object CMakeFiles/record-full.dir/record-full.cpp.o
/Users/alex/Documents/kbd-audio/record-full.cpp:9:10: fatal error: 'SDL2/SDL.h' file not found
#include <SDL2/SDL.h>
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/record-full.dir/record-full.cpp.o] Error 1
make[1]: *** [CMakeFiles/record-full.dir/all] Error 2
make: *** [all] Error 2
```

I have installed SDL2 with brew on mac and I find that sdl2 include path match to SDL2 folder and not include folder where SDL2 folder is.

**Comment by ggerganov** [comment]
Can you confirm that changing all instances of

    #include <SDL2/SDL.h>

to

    #include <SDL.h>

fixes the build?

**Comment by mirkorobocop** [comment]
@Its-Alex did you install libsdl2-dev package?

**Comment by Its-Alex** [comment]
@ggerganov Yes if i change this I can build it.

@mirkorobocop I'm under mac there is no package libsdl2-dev.
