### ISSUE TITLE
Continue training while demo'ing

### ISSUE THREAD

**Issue by PatMyron** [ggerganov/kbd-audio#10]
Is it possible to continue training after the demo has already started? The explicit training before the demo could even be removed and the demo could just get better over time.

**Comment by ggerganov** [comment]
You would have to keep typing within the application window, otherwise the program wouldn't know the ground-truth.

Another thing is, if you retrain from scratch with every new key, then training will become slower and slower (more and more data). So one has to figure out a smarter way to retrain.

I guess it's possible, but I don't really see a great benefit.
