### ISSUE TITLE
Identification

### ISSUE THREAD

**Issue by PACEJJ27** [ggerganov/kbd-audio#16]
Does it need to collect many kinds of keybords, such as a keybord used 3 years.
Different keybord may make different sound so as the keybord used very long time.

**Comment by ggerganov** [comment]
The `keytap` tool requires training data for a specific keyboard. Training on one keyboard and trying to predict on another will most likely fail (even if they are the same model/age/etc). You need to run it on the same keyboard on which you have collected the training data and also make sure to not change the position of the keyboard relative to the mic, because this also plays important role.
