### ISSUE TITLE
I have question 

### ISSUE THREAD

**Issue by themeswordpress** [ggerganov/kbd-audio#24]
please, I have a question, the first one is, the kbd tool it's a captures the characters from the keyboard using audio right? 
?? or its just capture the captures the characters using some of the keylogger technique and convert the text to audio???. 

the second one is if the first question true I mean if the tool can capture the characters from the keyboard using audio how can I use this tool to capture  from another device I mean how can i install it in devices 1 and capture  from devise 2

**Comment by ggerganov** [comment]
The keytap tool first captures both the audio and the pressed keys in order to collect training data. Then, it uses just audio to try to predict the pressed keys.

Currently, you have to train and predict on the same device. Training on one device and predicting on another is most likely won't work at all.
